paths:
  /api/products:
    get:
      summary: Get all products
      tags:
        - Products
      responses:
        "200":
          description: Products were returned successfully
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/ProductResponse"
        "500":
          description: Error on the server. Usually generating query or fail connection db
  
components:
  schemas:
    ProductResponse:
      type: object
      properties:
        status:
          type: string
          description: Estado de la respuesta
        msg:
          type: string
          description: Mensaje de la respuesta
        payload:
          type: array
          items:
            $ref: "#/components/schemas/Product"
    ProductResponseExample:
      status: "success"
      msg: "all products"
      payload:
        $ref: "#/components/examples/ProductExample"
    Product:
      type: object
      properties:
        _id:
          type: string
          description: ID auto generado por Mongo
        title:
          type: string
          description: Primer nombre
        description:
          type: string
          description: Descripción del producto
        code:
          type: number
          description: Código del producto
        price:
          type: number
          description: Precio del producto
        stock:
          type: number
          description: Cantidad en stock del producto
        category:
          type: string
          description: Categoría del producto
        thumbnail:
          type: string
          description: URL de la imagen del producto
    ProductExample:
      _id: "6488f0384ad256525b19b4c0"
      title: Orange
      description: rich , sweet and full of vitamin C
      code: 789
      price: 450
      stock: 136
      category: fruit
      thumbnail: https://s3.ppllstatics.com/elcorreo/www/multimedia/201902/08/media/cortadas/GF0N1J31-U401131236871ktC-U70573831277euB-624x385@El%20Correo-ElCorreo.jpg
    

